FROM node:latest
COPY . /app
WORKDIR /app
ARG JWT_SECRET="CHANGE_IT"
ENV JWT_SECRET=${JWT_SECRET}
ARG VK_API_ID="CHANGE_IT"
ARG VK_API_SECRET="CHANGE_IT"
ENV VK_API_ID=${VK_API_ID}
ENV VK_API_SECRET=${VK_API_SECRET}
ENV NODE_ENV="production"
ENV WRITE_STATS="true"
RUN npm i
RUN npm run build
CMD npm run server:start